#ifndef MESSAGEFILTER_GLOBAL_H
#define MESSAGEFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MESSAGEFILTER_LIBRARY)
#  define MESSAGEFILTER_EXPORT Q_DECL_EXPORT
#else
#  define MESSAGEFILTER_EXPORT Q_DECL_IMPORT
#endif

#endif // MESSAGEFILTER_GLOBAL_H
